modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
[[mixins]]
config="camp_checklist.mixins.json"
[[mods]]
modId="camp_checklist"
version="${mod_version}"
displayName="${mod_name}"
description="Datapack-driven shared world checklist."
[[dependencies.camp_checklist]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
side="BOTH"
[[dependencies.camp_checklist]]
modId="neoforge"
type="required"
versionRange="[21.1.219,)"
side="BOTH"
[[dependencies.camp_checklist]]
modId="ldlib2"
type="required"
versionRange="[2.2.38.a,)"
side="BOTH"
[[dependencies.camp_checklist]]
modId="pneumaticcraft"
type="optional"
versionRange="[8.2.23,)"
side="BOTH"
[[dependencies.camp_checklist]]
modId="create"
type="optional"
versionRange="[6.0.10,)"
side="BOTH"
